module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  background_image_formatter: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  comment: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fitvids: 0
  focal_point: 0
  image: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  media_thumbnails: 0
  media_thumbnails_video: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  ml_core: 0
  ml_migration: 0
  ml_user: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rate: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  responsive_menu: 0
  statistics: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  votingapi: 0
  pathauto: 1
  views: 10
  minimal: 1000
theme:
  seven: 0
  stable: 0
  classy: 0
  medialist: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
